---
- name: Remove ISO image
  block:
    - name: Remove ISO file from data_domain
      ovirt.ovirt.ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: "{{ iso_file }}"
        storage_domain: "{{ providers.ovirt.data_domain | default('data_domain') }}"
        state: absent
  rescue:
    - name: Include wait_iso_disk_unlock_pre29
      ansible.builtin.include_tasks: wait_iso_disk_unlock_pre29.yml
      when: ansible_version.full is version('2.9', '<')

    - name: Include wait_iso_disk_unlock
      ansible.builtin.include_tasks: wait_iso_disk_unlock.yml
      when: ansible_version.full is version('2.9', '>=')

    - name: Remove ISO file from data_domain
      ovirt.ovirt.ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: "{{ iso_file }}"
        storage_domain: "{{ providers.ovirt.data_domain | default('data_domain') }}"
        state: absent
