---

- name: Obtain SSO token with using username/password credentials
  ovirt.ovirt.ovirt_auth:
    url: "{{ lookup('env', 'OVIRT_URL') | default(ovirt.url, true) }}"
    username: "{{ lookup('env', 'OVIRT_USERNAME') | default(ovirt.username, true) }}"
    password: "{{ lookup('env', 'OVIRT_PASSWORD') | default(ovirt.password, true) }}"
    insecure: true

- name: Include preflight_check_pre29
  ansible.builtin.include_tasks: preflight_check_pre29.yml
  when: ansible_version.full is version('2.9', '<')

- name: Include preflight_check
  ansible.builtin.include_tasks: preflight_check.yml
  when: ansible_version.full is version('2.9', '>=')

# remove existing template
- name: Remove existing template
  block:

    - name: Include remove_template
      ansible.builtin.include_tasks: remove_template.yml

  when:
    - template_force | bool
    - template_found | bool

- name: Main task block
  block:
    - name: Include make_iso
      ansible.builtin.include_tasks: make_iso.yml

    - name: Include provision_vm
      ansible.builtin.include_tasks: provision_vm.yml

    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory

    - name: Clear gathered facts
      ansible.builtin.meta: clear_facts

    - name: Clear any host errors
      ansible.builtin.meta: clear_host_errors

    - name: Add host
      ansible.builtin.add_host:
        hostname: template_vm
        ansible_host: '{{ template_vm_ip_address }}'
        host_key_checking: false
        ansible_user: "{{ local_account_username }}"
        ansible_password: "{{ local_account_password }}"
        ansible_port: "{{ vm_ansible_port | default('22') }}"
        ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'
        ansible_python_interpreter: auto

    - name: Run setup module
      ansible.builtin.setup:
      delegate_to: template_vm
      connection: ssh

    - name: Role tasks
      block:
        - name: Include oatakan.rhn role (register)
          ansible.builtin.include_role:
            name: oatakan.rhn
            apply:
              delegate_to: template_vm
              connection: ssh
              become: true
          vars:
            rhel_ovirt_template_role_action: register

        - name: Include oatakan.rhel_upgrade role
          ansible.builtin.include_role:
            name: oatakan.rhel_upgrade
            apply:
              delegate_to: template_vm
              connection: ssh
              become: true
          when: install_updates | bool

        - name: Include oatakan.rhel_template_build role
          ansible.builtin.include_role:
            name: oatakan.rhel_template_build
            apply:
              delegate_to: template_vm
              connection: ssh
              become: true
              vars:
                target_ovirt: true

      always:
        - name: Include oatakan.rhn role (unregister)
          ansible.builtin.include_role:
            name: oatakan.rhn
            apply:
              delegate_to: template_vm
              connection: ssh
              become: true
          vars:
            rhel_ovirt_template_role_action: unregister

    - name: Force handlers to run before stoppping the vm
      ansible.builtin.meta: flush_handlers

    - name: Refresh SSO credentials
      ovirt.ovirt.ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') | default(ovirt.url, true) }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') | default(ovirt.username, true) }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') | default(ovirt.password, true) }}"
        insecure: true

    - name: Include stop_vm
      ansible.builtin.include_tasks: stop_vm.yml

    - name: Include convert_to_template
      ansible.builtin.include_tasks: convert_to_template.yml

    - name: Include export_ovf
      ansible.builtin.include_tasks: export_ovf.yml
      when: export_ovf | bool

  rescue:
    - name: Refresh SSO credentials (rescue)
      ovirt.ovirt.ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') | default(ovirt.url, true) }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') | default(ovirt.username, true) }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') | default(ovirt.password, true) }}"
        insecure: true

    - name: Include remove_template (rescue)
      ansible.builtin.include_tasks: remove_template.yml
      when: remove_vm_on_error | bool

  always:
    - name: Refresh SSO credentials (always)
      ovirt.ovirt.ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') | default(ovirt.url, true) }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') | default(ovirt.username, true) }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') | default(ovirt.password, true) }}"
        insecure: true

    - name: Include remove_vm
      ansible.builtin.include_tasks: remove_vm.yml

    - name: Include datastore_iso_remove
      ansible.builtin.include_tasks: datastore_iso_remove.yml

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ temp_directory }}"
        state: absent

    - name: Logout from oVirt
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
