---
- name: Make ISO
  block:
    - name: Create temporary directory
      ansible.builtin.file:
        path: "{{ temp_directory }}/ks_iso"
        state: directory
        mode: "0755"

    - name: Create ks.cfg file
      ansible.builtin.template:
        src: "{{ linux_ks_folder }}/ks.cfg.j2"
        dest: "{{ temp_directory }}/ks_iso/ks.cfg"
        mode: "0644"

    - name: Create ISO
      ansible.builtin.command: >
        mkisofs -U -A "OEMDRV" -V "OEMDRV"
        -volset "OEMDRV" -J -joliet-long -r -v -T
        -o {{ playbook_dir }}/{{ temp_directory }}/linux_{{ distro_name }}_ks_autogen.iso .
      args:
        chdir: "{{ playbook_dir }}/{{ temp_directory }}/ks_iso"
      changed_when: false

    - name: Include datastore_upload
      ansible.builtin.include_tasks: datastore_upload.yml
  always:
    - name: Remove temporary files
      ansible.builtin.file:
        path: "{{ temp_directory }}/{{ item }}"
        state: absent
      loop:
        - linux_{{ distro_name }}_ks_autogen.iso
        - ks_iso/
