---
- name: Get the datacenter name (<2.9)
  community.general.ovirt_datacenter_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "Clusters.name = {{ providers.ovirt.cluster }}"

- name: Get storage information (<2.9)
  community.general.ovirt_storage_domain_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ ovirt_datacenters[0].name }}"
  when:
    - template_disk_storage is undefined

- name: Get data domain (<2.9)
  ansible.builtin.set_fact:
    disk_storage_domain: "{{ ovirt_storage_domains | json_query(the_query) | list | first | default({}) }}"
  when:
    - template_disk_storage is undefined
  vars:
    the_query: "[?type=='data']"

- name: Get ISO domain (deprecated as of oVirt/RHV 4.3)
  ansible.builtin.set_fact:
    iso_domain: "{{ ovirt_storage_domains | json_query(the_query) | list | first | default({}) }}"
  vars:
    the_query: "[?type=='iso']"

- name: Check if template already exists (<2.9)
  community.general.ovirt_template_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ template.name }} and datacenter={{ ovirt_datacenters[0].name }}"

- name: Handle existing template (<2.9)
  when:
    - ovirt_templates is defined
    - ovirt_templates | length > 0

  block:
    - name: Set template_found to true
      ansible.builtin.set_fact:
        template_found: true

    - name: Fail with message
      ansible.builtin.fail:
        msg: "Existing template found on ovirt/rhv: {{ template.name }}"
      when: not template_force | bool
- name: Check ISO file on data domain (<2.9)
  community.general.ovirt_disk_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ iso_file_name }}"
  when: iso_file_name is defined

- name: Set file id of the ISO file (<2.9)
  ansible.builtin.set_fact:
    iso_file_id: "{{ ovirt_disks[0].id }}"
  when:
    - ovirt_disks | length > 0
    - ovirt_disks[0].id is defined
    - ovirt_disks[0].content_type == 'iso'

- name: Fail with message if ISO not found (<2.9)
  ansible.builtin.fail:
    msg: "iso file ({{ template.name }}) could not be found on the data domain and iso domain does not exists"
  when:
    - iso_file_id is undefined
    - iso_domain is undefined or iso_domain | length == 0
