---

- name: Stop VM tasks
  block:

    - name: Shutdown guest VM
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "{{ providers.ovirt.cluster }}"
        name: "{{ template.name }}"
        state: stopped
      async: 7200
      poll: 0
      register: shutdown
      when: template is defined

    - name: Wait for server to stop responding
      ansible.builtin.wait_for:
        host: "{{ template_vm_ip_address }}"
        port: "{{ vm_ansible_port | default('22') }}"
        timeout: 120
        state: stopped

    - name: Include wait_vm_poweredoff_pre29
      ansible.builtin.include_tasks: wait_vm_poweredoff_pre29.yml
      when: ansible_version.full is version('2.9', '<')

    - name: Include wait_vm_poweredoff
      ansible.builtin.include_tasks: wait_vm_poweredoff.yml
      when: ansible_version.full is version('2.9', '>=')

  rescue:
    - name: Ignoring any error
      ansible.builtin.debug:
        msg: "ignoring error..."

- name: Reconfigure VM
  ovirt.ovirt.ovirt_vm:
    auth: "{{ ovirt_auth }}"
    cluster: "{{ providers.ovirt.cluster }}"
    name: "{{ template.name }}"
    boot_devices:
      - hd
    cd_iso: ""
    custom_properties: "{{ custom_properties_efi if (template_vm_efi | bool and custom_efi_enabled | bool) else ([{}]) }}"
    force: true
    state: present
  when: template is defined
